# Generated by Django 2.2.7 on 2019-12-20 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20191219_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='author',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
