# Generated by Django 2.2.7 on 2019-12-21 18:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_auto_20191222_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='date_created',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 12, 22, 2, 17, 36, 557144)),
        ),
    ]
