# Generated by Django 2.2.7 on 2019-12-21 18:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_auto_20191222_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='date_created',
            field=models.DateTimeField(null=True, verbose_name=datetime.datetime(2019, 12, 22, 2, 18, 39, 558404)),
        ),
    ]
