# Generated by Django 2.2.7 on 2019-12-21 18:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_auto_20191222_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='date_created',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 12, 21, 18, 25, 54, 45728, tzinfo=utc)),
        ),
    ]
