# Generated by Django 2.2.7 on 2019-12-21 18:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0010_auto_20191222_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 12, 21, 18, 33, 15, 845295, tzinfo=utc), editable=False),
        ),
    ]
