# Generated by Django 2.2.7 on 2019-12-21 18:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0012_auto_20191222_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='date_created',
            field=models.DateTimeField(null=True, verbose_name=datetime.datetime(2019, 12, 21, 18, 55, 55, 399101, tzinfo=utc)),
        ),
    ]
