# Generated by Django 2.2.7 on 2019-12-22 03:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0013_auto_20191222_0255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='date_created',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 12, 22, 3, 8, 51, 944898)),
        ),
    ]
