# Generated by Django 2.2.7 on 2019-12-22 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0015_auto_20191222_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
